export const demoOverlayCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.828, 1.296],
          [103.844, 1.296],
          [103.844, 1.308],
          [103.828, 1.308],
          [103.828, 1.296],
        ]],
      },
      properties: {
        planningAreaId: "demo-orchard",
        planningAreaName: "Orchard",
        areaCode: "ORCHARD",
        regionName: "Central",
        composite: 84,
        demographics: 78,
        accessibility: 93,
        vacancy: 61,
        populationTotal: 82000,
        effectiveYear: 2025,
        busStopCount: 58,
        mrtExitCount: 9,
        avgUnitPricePsf: 31,
        retailTransactionCount: 44,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.815, 1.277],
          [103.831, 1.277],
          [103.831, 1.289],
          [103.815, 1.289],
          [103.815, 1.277],
        ]],
      },
      properties: {
        planningAreaId: "demo-tiong-bahru",
        planningAreaName: "Tiong Bahru",
        areaCode: "TIONG_BAHRU",
        regionName: "Central",
        composite: 76,
        demographics: 72,
        accessibility: 82,
        vacancy: 74,
        populationTotal: 64500,
        effectiveYear: 2025,
        busStopCount: 41,
        mrtExitCount: 5,
        avgUnitPricePsf: 24,
        retailTransactionCount: 22,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.729, 1.325],
          [103.754, 1.325],
          [103.754, 1.347],
          [103.729, 1.347],
          [103.729, 1.325],
        ]],
      },
      properties: {
        planningAreaId: "demo-jurong-east",
        planningAreaName: "Jurong East",
        areaCode: "JURONG_EAST",
        regionName: "West",
        composite: 88,
        demographics: 81,
        accessibility: 90,
        vacancy: 78,
        populationTotal: 90500,
        effectiveYear: 2025,
        busStopCount: 63,
        mrtExitCount: 8,
        avgUnitPricePsf: 22,
        retailTransactionCount: 31,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.887, 1.312],
          [103.905, 1.312],
          [103.905, 1.329],
          [103.887, 1.329],
          [103.887, 1.312],
        ]],
      },
      properties: {
        planningAreaId: "demo-paya-lebar",
        planningAreaName: "Paya Lebar",
        areaCode: "PAYA_LEBAR",
        regionName: "East",
        composite: 82,
        demographics: 75,
        accessibility: 87,
        vacancy: 67,
        populationTotal: 71100,
        effectiveYear: 2025,
        busStopCount: 55,
        mrtExitCount: 7,
        avgUnitPricePsf: 28,
        retailTransactionCount: 29,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.938, 1.343],
          [103.963, 1.343],
          [103.963, 1.365],
          [103.938, 1.365],
          [103.938, 1.343],
        ]],
      },
      properties: {
        planningAreaId: "demo-tampines",
        planningAreaName: "Tampines",
        areaCode: "TAMPINES",
        regionName: "East",
        composite: 79,
        demographics: 85,
        accessibility: 76,
        vacancy: 69,
        populationTotal: 118000,
        effectiveYear: 2025,
        busStopCount: 52,
        mrtExitCount: 4,
        avgUnitPricePsf: 27,
        retailTransactionCount: 19,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [[
          [103.772, 1.428],
          [103.795, 1.428],
          [103.795, 1.447],
          [103.772, 1.447],
          [103.772, 1.428],
        ]],
      },
      properties: {
        planningAreaId: "demo-woodlands",
        planningAreaName: "Woodlands",
        areaCode: "WOODLANDS",
        regionName: "North",
        composite: 74,
        demographics: 88,
        accessibility: 65,
        vacancy: 73,
        populationTotal: 132000,
        effectiveYear: 2025,
        busStopCount: 37,
        mrtExitCount: 3,
        avgUnitPricePsf: 23,
        retailTransactionCount: 16,
      },
    },
  ],
  metadata: {
    availableMetrics: {
      composite: true,
      demographics: true,
      accessibility: true,
      vacancy: true,
    },
    requestedMetric: "composite",
    featureCount: 6,
    source: "demo",
  },
} as const;

export const demoPointLayers = {
  mrtStations: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.839, 1.303] },
        properties: {
          stationName: "Orchard",
          lineName: "North-South / Thomson-East Coast",
          exitCount: 6,
          label: "Orchard station",
        },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.823, 1.286] },
        properties: {
          stationName: "Tiong Bahru",
          lineName: "East-West",
          exitCount: 4,
          label: "Tiong Bahru station",
        },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.742, 1.333] },
        properties: {
          stationName: "Jurong East",
          lineName: "North-South / East-West",
          exitCount: 7,
          label: "Jurong East station",
        },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.893, 1.318] },
        properties: {
          stationName: "Paya Lebar",
          lineName: "East-West / Circle",
          exitCount: 5,
          label: "Paya Lebar station",
        },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.946, 1.354] },
        properties: {
          stationName: "Tampines",
          lineName: "East-West / Downtown",
          exitCount: 4,
          label: "Tampines station",
        },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.786, 1.437] },
        properties: {
          stationName: "Woodlands",
          lineName: "North-South / Thomson-East Coast",
          exitCount: 4,
          label: "Woodlands station",
        },
      },
    ],
    metadata: {
      layer: "mrt-stations",
      featureCount: 6,
      source: "demo",
    },
  },
  mrtExits: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.839, 1.304] },
        properties: { stationName: "Orchard", exitNumber: "A", label: "Orchard Exit A" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.823, 1.285] },
        properties: { stationName: "Tiong Bahru", exitNumber: "A", label: "Tiong Bahru Exit A" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.742, 1.333] },
        properties: { stationName: "Jurong East", exitNumber: "B", label: "Jurong East Exit B" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.893, 1.318] },
        properties: { stationName: "Paya Lebar", exitNumber: "D", label: "Paya Lebar Exit D" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.946, 1.354] },
        properties: { stationName: "Tampines", exitNumber: "C", label: "Tampines Exit C" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.786, 1.437] },
        properties: { stationName: "Woodlands", exitNumber: "A", label: "Woodlands Exit A" },
      },
    ],
    metadata: {
      layer: "mrt-exits",
      featureCount: 6,
      source: "demo",
    },
  },
  busStops: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.836, 1.301] },
        properties: { busStopNumber: "09011", label: "Bus stop 09011" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.841, 1.306] },
        properties: { busStopNumber: "09012", label: "Bus stop 09012" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.821, 1.283] },
        properties: { busStopNumber: "10111", label: "Bus stop 10111" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.746, 1.338] },
        properties: { busStopNumber: "28009", label: "Bus stop 28009" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.899, 1.323] },
        properties: { busStopNumber: "81231", label: "Bus stop 81231" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.951, 1.359] },
        properties: { busStopNumber: "76159", label: "Bus stop 76159" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.782, 1.441] },
        properties: { busStopNumber: "46031", label: "Bus stop 46031" },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [103.789, 1.434] },
        properties: { busStopNumber: "46039", label: "Bus stop 46039" },
      },
    ],
    metadata: {
      layer: "bus-stops",
      featureCount: 8,
      source: "demo",
    },
  },
} as const;
