@startuml UC_07_Individual
left to right direction
!theme plain
skinparam backgroundColor #FEFEFE
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #E3F2FD
  BorderColor #1565C0
  FontSize 11
}

title UC-07: View Business Profiles

actor "User\n(A01/A02/A03)" as USER
actor "System Backend\n(A04)" as A04

rectangle "SmartLocateSG" {
  usecase "UC-07 View Business Profiles" as UC07

}

USER --> UC07
A04 --> UC07



note right of UC07
Pre: Refer corresponding sequence precondition.
Flow: Main interaction follows sequence messages.
AC/EX: Alternate and exception branches traced from sequence.
end note

@enduml
